index_vec = floor(logspace(0,log10(length(t)),n_traces));
ii=0; % for printing sim progress
options = ...
    odeset( ...
        'AbsTol',1e-8, ...
        'RelTol',1e-5 ...
    );
sol =   pdepe(m, ...
        @sim_pde, ...
        @sim_ic, ...
        @sim_bc, ...
        rr, ...
        t, ...
        options);
    
